---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-troubleshooter-v8-sa
  namespace: ai-troubleshooter-v8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-troubleshooter-v8-reader
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - pods/log
    - events
    - persistentvolumeclaims
    - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - statefulsets
  verbs: ["get", "list"]
- apiGroups: ["route.openshift.io"]
  resources:
    - routes
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-troubleshooter-v8-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ai-troubleshooter-v8-reader
subjects:
- kind: ServiceAccount
  name: ai-troubleshooter-v8-sa
  namespace: ai-troubleshooter-v8

