---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-troubleshooter-v8-sa
  namespace: ai-troubleshooter-v8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-troubleshooter-v8-reader
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - pods/log
    - events
    - persistentvolumeclaims
    - services
    - configmaps
    - secrets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["route.openshift.io"]
  resources:
    - routes
  verbs: ["get", "list", "watch"]
- apiGroups: ["serving.kserve.io"]
  resources:
    - inferenceservices
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
    - pods
    - nodes
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-troubleshooter-v8-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ai-troubleshooter-v8-reader
subjects:
- kind: ServiceAccount
  name: ai-troubleshooter-v8-sa
  namespace: ai-troubleshooter-v8


