apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ocp-mcp-server"},"name":"ocp-mcp-server","namespace":"model"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ocp-mcp-server"}},"template":{"metadata":{"labels":{"app":"ocp-mcp-server","deployment":"ocp-mcp-server"}},"spec":{"containers":[{"args":["--sse-port","8000"],"command":["./kubernetes-mcp-server"],"image":"quay.io/njajodia/ocp-mcp-server:latest","name":"ocp-mcp-server","ports":[{"containerPort":8000,"name":"http","protocol":"TCP"}],"resources":{}}],"serviceAccountName":"ocp-mcp"}}}}
  creationTimestamp: "2025-10-05T09:48:25Z"
  generation: 3
  labels:
    app: ocp-mcp-server
  name: ocp-mcp-server
  namespace: model
  resourceVersion: "43310490"
  uid: 3b4f05dc-af65-4c9c-9a07-066515127ff5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocp-mcp-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: opentelemetrycollector/auto-instrumentation
        instrumentation.opentelemetry.io/python-container-names: ocp-mcp-server
        kubectl.kubernetes.io/restartedAt: "2025-10-06T11:53:39+08:00"
      creationTimestamp: null
      labels:
        app: ocp-mcp-server
        deployment: ocp-mcp-server
    spec:
      containers:
      - args:
        - --sse-port
        - "8000"
        command:
        - ./kubernetes-mcp-server
        image: quay.io/njajodia/ocp-mcp-server:latest
        imagePullPolicy: Always
        name: ocp-mcp-server
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ocp-mcp
      serviceAccountName: ocp-mcp
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-05T09:48:25Z"
    lastUpdateTime: "2025-10-06T03:55:46Z"
    message: ReplicaSet "ocp-mcp-server-7cfd5c6864" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-09T12:59:02Z"
    lastUpdateTime: "2025-10-09T12:59:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
